variables:
    IMAGE_NAME: $REGISTRY_USER/photographer-amin-ui

stages:
     - build

build_image:
    stage: build
    image: docker
    services:
        - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    script:
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
